export interface ZoneDescription { name: string, desc: string, edge: string }

export const zoneDescriptions: Record<string, ZoneDescription> = {
  'pass-line': { name: 'Pass Line', desc: 'Bet with the shooter. Wins on 7/11, loses on 2/3/12 (come-out). After point: wins if point rolls before 7.', edge: '1.41%' },
  'dont-pass': { name: 'Don\'t Pass', desc: 'Bet against the shooter. Wins on 2/3, pushes on 12 (come-out). After point: wins if 7 rolls before point.', edge: '1.36%' },
  'come': { name: 'Come', desc: 'Like a new Pass Line bet during point phase. Next roll: 7/11 wins, 2/3/12 loses, anything else establishes your Come point.', edge: '1.41%' },
  'dont-come': { name: 'Don\'t Come', desc: 'Like a new Don\'t Pass during point phase. Next roll: 2/3 wins, 12 pushes, 7/11 loses, anything else establishes point.', edge: '1.36%' },
  'field': { name: 'Field', desc: 'One-roll bet. Wins on 2,3,4,9,10,11,12. Loses on 5,6,7,8. Bonus payouts on 2 (2:1) and 12 (3:1).', edge: '2.78%' },
  'pass-odds': { name: 'Pass Odds', desc: 'Extra bet behind Pass Line at true odds. ZERO house edge. Only available after point is set. Always max your odds!', edge: '0%' },
  'dont-pass-odds': { name: 'Don\'t Pass Odds', desc: 'Lay odds behind Don\'t Pass at true odds. Zero house edge.', edge: '0%' },
  'come-odds': { name: 'Come Odds', desc: 'Odds behind an established Come bet. Zero house edge.', edge: '0%' },
  'dont-come-odds': { name: 'Don\'t Come Odds', desc: 'Odds behind an established Don\'t Come bet. Zero house edge.', edge: '0%' },
  'place-4': { name: 'Place 4', desc: 'Bet that 4 rolls before 7. Pays 9:5.', edge: '6.67%' },
  'place-5': { name: 'Place 5', desc: 'Bet that 5 rolls before 7. Pays 7:5.', edge: '4.00%' },
  'place-six': { name: 'Place 6', desc: 'Bet that 6 rolls before 7. Pays 7:6. One of the best Place bets.', edge: '1.52%' },
  'place-8': { name: 'Place 8', desc: 'Bet that 8 rolls before 7. Pays 7:6. One of the best Place bets.', edge: '1.52%' },
  'place-nine': { name: 'Place 9', desc: 'Bet that 9 rolls before 7. Pays 7:5.', edge: '4.00%' },
  'place-10': { name: 'Place 10', desc: 'Bet that 10 rolls before 7. Pays 9:5.', edge: '6.67%' },
  'big-6': { name: 'Big 6', desc: 'Bet 6 rolls before 7. Pays only 1:1 — Place 6 pays 7:6 for the same bet. This is a sucker bet.', edge: '9.09%' },
  'big-8': { name: 'Big 8', desc: 'Bet 8 rolls before 7. Pays only 1:1 — Place 8 pays 7:6 for the same bet. This is a sucker bet.', edge: '9.09%' },
  'hard-4': { name: 'Hard 4', desc: 'Bet that 2+2 rolls before any other 4 or 7. Pays 7:1.', edge: '11.11%' },
  'hard-6': { name: 'Hard 6', desc: 'Bet that 3+3 rolls before any other 6 or 7. Pays 9:1.', edge: '9.09%' },
  'hard-8': { name: 'Hard 8', desc: 'Bet that 4+4 rolls before any other 8 or 7. Pays 9:1.', edge: '9.09%' },
  'hard-10': { name: 'Hard 10', desc: 'Bet that 5+5 rolls before any other 10 or 7. Pays 7:1.', edge: '11.11%' },
  'any-seven': { name: 'Any Seven', desc: 'One-roll bet that the next roll is 7. Pays 4:1. Worst bet on the table.', edge: '16.67%' },
  'any-craps': { name: 'Any Craps', desc: 'One-roll bet on 2, 3, or 12. Pays 7:1.', edge: '11.11%' },
  'aces': { name: 'Aces (Snake Eyes)', desc: 'One-roll bet on 2. Pays 30:1. Very rare hit (1 in 36).', edge: '13.89%' },
  'ace-deuce': { name: 'Ace-Deuce', desc: 'One-roll bet on 3. Pays 15:1.', edge: '11.11%' },
  'yo-eleven': { name: 'Yo (Eleven)', desc: 'One-roll bet on 11. Pays 15:1.', edge: '11.11%' },
  'boxcars': { name: 'Boxcars (Midnight)', desc: 'One-roll bet on 12. Pays 30:1. Very rare hit (1 in 36).', edge: '13.89%' },
  'craps-eleven': { name: 'C & E', desc: 'One-roll bet on any craps (2/3/12) or eleven. Pays 3:1 on craps, 7:1 on eleven.', edge: '11.11%' },
  'horn': { name: 'Horn', desc: '4-unit one-roll bet: $1 each on 2, 3, 11, 12. Wins 30:1 or 15:1 minus 3 losing units.', edge: '12.50%' },
  'horn-high': { name: 'Horn High (Yo)', desc: '5-unit one-roll bet: 2 units on 11 (the "high"), 1 unit each on 2, 3, 12. The doubled unit pays only when 11 rolls.', edge: '12.22%' },
  'hop-easy': { name: 'Hop (Easy)', desc: 'One-roll bet on a specific non-pair combo. Pays 15:1.', edge: '11.11%' },
  'hop-hard': { name: 'Hop (Hard)', desc: 'One-roll bet on a specific pair combo. Pays 30:1.', edge: '13.89%' }
}
